package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BusinessUnitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUnitAllPropertiesEquals(BusinessUnit expected, BusinessUnit actual) {
        assertBusinessUnitAutoGeneratedPropertiesEquals(expected, actual);
        assertBusinessUnitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUnitAllUpdatablePropertiesEquals(BusinessUnit expected, BusinessUnit actual) {
        assertBusinessUnitUpdatableFieldsEquals(expected, actual);
        assertBusinessUnitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUnitAutoGeneratedPropertiesEquals(BusinessUnit expected, BusinessUnit actual) {
        assertThat(actual)
            .as("Verify BusinessUnit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUnitUpdatableFieldsEquals(BusinessUnit expected, BusinessUnit actual) {
        assertThat(actual)
            .as("Verify BusinessUnit relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusinessUnitUpdatableRelationshipsEquals(BusinessUnit expected, BusinessUnit actual) {
        assertThat(actual)
            .as("Verify BusinessUnit relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
