package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EquipmentComponentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentComponentAllPropertiesEquals(EquipmentComponent expected, EquipmentComponent actual) {
        assertEquipmentComponentAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipmentComponentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentComponentAllUpdatablePropertiesEquals(EquipmentComponent expected, EquipmentComponent actual) {
        assertEquipmentComponentUpdatableFieldsEquals(expected, actual);
        assertEquipmentComponentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentComponentAutoGeneratedPropertiesEquals(EquipmentComponent expected, EquipmentComponent actual) {
        assertThat(actual)
            .as("Verify EquipmentComponent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentComponentUpdatableFieldsEquals(EquipmentComponent expected, EquipmentComponent actual) {
        assertThat(actual)
            .as("Verify EquipmentComponent relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentComponentUpdatableRelationshipsEquals(EquipmentComponent expected, EquipmentComponent actual) {
        assertThat(actual)
            .as("Verify EquipmentComponent relationships")
            .satisfies(a ->
                assertThat(a.getComponentTemperatureLimits())
                    .as("check componentTemperatureLimits")
                    .isEqualTo(expected.getComponentTemperatureLimits())
            )
            .satisfies(a -> assertThat(a.getEquipments()).as("check equipments").isEqualTo(expected.getEquipments()));
    }
}
