package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EquipmentComponentTemperatureLimitsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentComponentTemperatureLimitsAllPropertiesEquals(
        EquipmentComponentTemperatureLimits expected,
        EquipmentComponentTemperatureLimits actual
    ) {
        assertEquipmentComponentTemperatureLimitsAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipmentComponentTemperatureLimitsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentComponentTemperatureLimitsAllUpdatablePropertiesEquals(
        EquipmentComponentTemperatureLimits expected,
        EquipmentComponentTemperatureLimits actual
    ) {
        assertEquipmentComponentTemperatureLimitsUpdatableFieldsEquals(expected, actual);
        assertEquipmentComponentTemperatureLimitsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentComponentTemperatureLimitsAutoGeneratedPropertiesEquals(
        EquipmentComponentTemperatureLimits expected,
        EquipmentComponentTemperatureLimits actual
    ) {
        assertThat(actual)
            .as("Verify EquipmentComponentTemperatureLimits auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentComponentTemperatureLimitsUpdatableFieldsEquals(
        EquipmentComponentTemperatureLimits expected,
        EquipmentComponentTemperatureLimits actual
    ) {
        assertThat(actual)
            .as("Verify EquipmentComponentTemperatureLimits relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getNormal()).as("check normal").isEqualTo(expected.getNormal()))
            .satisfies(a -> assertThat(a.getLowRisk()).as("check lowRisk").isEqualTo(expected.getLowRisk()))
            .satisfies(a -> assertThat(a.getMediumRisk()).as("check mediumRisk").isEqualTo(expected.getMediumRisk()))
            .satisfies(a -> assertThat(a.getHighRisk()).as("check highRisk").isEqualTo(expected.getHighRisk()))
            .satisfies(a -> assertThat(a.getImminentHighRisk()).as("check imminentHighRisk").isEqualTo(expected.getImminentHighRisk()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentComponentTemperatureLimitsUpdatableRelationshipsEquals(
        EquipmentComponentTemperatureLimits expected,
        EquipmentComponentTemperatureLimits actual
    ) {
        // empty method
    }
}
