package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EquipmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAllPropertiesEquals(Equipment expected, Equipment actual) {
        assertEquipmentAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAllUpdatablePropertiesEquals(Equipment expected, Equipment actual) {
        assertEquipmentUpdatableFieldsEquals(expected, actual);
        assertEquipmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentAutoGeneratedPropertiesEquals(Equipment expected, Equipment actual) {
        assertThat(actual)
            .as("Verify Equipment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentUpdatableFieldsEquals(Equipment expected, Equipment actual) {
        assertThat(actual)
            .as("Verify Equipment relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getManufacturer()).as("check manufacturer").isEqualTo(expected.getManufacturer()))
            .satisfies(a -> assertThat(a.getModel()).as("check model").isEqualTo(expected.getModel()))
            .satisfies(a -> assertThat(a.getSerialNumber()).as("check serialNumber").isEqualTo(expected.getSerialNumber()))
            .satisfies(a -> assertThat(a.getVoltageClass()).as("check voltageClass").isEqualTo(expected.getVoltageClass()))
            .satisfies(a -> assertThat(a.getPhaseType()).as("check phaseType").isEqualTo(expected.getPhaseType()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentUpdatableRelationshipsEquals(Equipment expected, Equipment actual) {
        assertThat(actual)
            .as("Verify Equipment relationships")
            .satisfies(a -> assertThat(a.getPlant()).as("check plant").isEqualTo(expected.getPlant()))
            .satisfies(a -> assertThat(a.getGroup()).as("check group").isEqualTo(expected.getGroup()))
            .satisfies(a -> assertThat(a.getComponents()).as("check components").isEqualTo(expected.getComponents()));
    }
}
