package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EquipmentGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentGroupAllPropertiesEquals(EquipmentGroup expected, EquipmentGroup actual) {
        assertEquipmentGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipmentGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentGroupAllUpdatablePropertiesEquals(EquipmentGroup expected, EquipmentGroup actual) {
        assertEquipmentGroupUpdatableFieldsEquals(expected, actual);
        assertEquipmentGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentGroupAutoGeneratedPropertiesEquals(EquipmentGroup expected, EquipmentGroup actual) {
        assertThat(actual)
            .as("Verify EquipmentGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentGroupUpdatableFieldsEquals(EquipmentGroup expected, EquipmentGroup actual) {
        assertThat(actual)
            .as("Verify EquipmentGroup relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentGroupUpdatableRelationshipsEquals(EquipmentGroup expected, EquipmentGroup actual) {
        assertThat(actual)
            .as("Verify EquipmentGroup relationships")
            .satisfies(a -> assertThat(a.getPlant()).as("check plant").isEqualTo(expected.getPlant()))
            .satisfies(a -> assertThat(a.getParentGroup()).as("check parentGroup").isEqualTo(expected.getParentGroup()));
    }
}
