package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EquipmentTypeTranslationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentTypeTranslationAllPropertiesEquals(
        EquipmentTypeTranslation expected,
        EquipmentTypeTranslation actual
    ) {
        assertEquipmentTypeTranslationAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipmentTypeTranslationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentTypeTranslationAllUpdatablePropertiesEquals(
        EquipmentTypeTranslation expected,
        EquipmentTypeTranslation actual
    ) {
        assertEquipmentTypeTranslationUpdatableFieldsEquals(expected, actual);
        assertEquipmentTypeTranslationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentTypeTranslationAutoGeneratedPropertiesEquals(
        EquipmentTypeTranslation expected,
        EquipmentTypeTranslation actual
    ) {
        assertThat(actual)
            .as("Verify EquipmentTypeTranslation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentTypeTranslationUpdatableFieldsEquals(
        EquipmentTypeTranslation expected,
        EquipmentTypeTranslation actual
    ) {
        assertThat(actual)
            .as("Verify EquipmentTypeTranslation relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipmentTypeTranslationUpdatableRelationshipsEquals(
        EquipmentTypeTranslation expected,
        EquipmentTypeTranslation actual
    ) {
        // empty method
    }
}
