package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InspectionRouteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteAllPropertiesEquals(InspectionRoute expected, InspectionRoute actual) {
        assertInspectionRouteAutoGeneratedPropertiesEquals(expected, actual);
        assertInspectionRouteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteAllUpdatablePropertiesEquals(InspectionRoute expected, InspectionRoute actual) {
        assertInspectionRouteUpdatableFieldsEquals(expected, actual);
        assertInspectionRouteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteAutoGeneratedPropertiesEquals(InspectionRoute expected, InspectionRoute actual) {
        assertThat(actual)
            .as("Verify InspectionRoute auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteUpdatableFieldsEquals(InspectionRoute expected, InspectionRoute actual) {
        assertThat(actual)
            .as("Verify InspectionRoute relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPlanNote()).as("check planNote").isEqualTo(expected.getPlanNote()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getStarted()).as("check started").isEqualTo(expected.getStarted()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getFinished()).as("check finished").isEqualTo(expected.getFinished()))
            .satisfies(a -> assertThat(a.getFinishedAt()).as("check finishedAt").isEqualTo(expected.getFinishedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteUpdatableRelationshipsEquals(InspectionRoute expected, InspectionRoute actual) {
        assertThat(actual)
            .as("Verify InspectionRoute relationships")
            .satisfies(a -> assertThat(a.getPlant()).as("check plant").isEqualTo(expected.getPlant()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getStartedBy()).as("check startedBy").isEqualTo(expected.getStartedBy()))
            .satisfies(a -> assertThat(a.getFinishedBy()).as("check finishedBy").isEqualTo(expected.getFinishedBy()));
    }
}
