package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InspectionRouteGroupEquipmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteGroupEquipmentAllPropertiesEquals(
        InspectionRouteGroupEquipment expected,
        InspectionRouteGroupEquipment actual
    ) {
        assertInspectionRouteGroupEquipmentAutoGeneratedPropertiesEquals(expected, actual);
        assertInspectionRouteGroupEquipmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteGroupEquipmentAllUpdatablePropertiesEquals(
        InspectionRouteGroupEquipment expected,
        InspectionRouteGroupEquipment actual
    ) {
        assertInspectionRouteGroupEquipmentUpdatableFieldsEquals(expected, actual);
        assertInspectionRouteGroupEquipmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteGroupEquipmentAutoGeneratedPropertiesEquals(
        InspectionRouteGroupEquipment expected,
        InspectionRouteGroupEquipment actual
    ) {
        assertThat(actual)
            .as("Verify InspectionRouteGroupEquipment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteGroupEquipmentUpdatableFieldsEquals(
        InspectionRouteGroupEquipment expected,
        InspectionRouteGroupEquipment actual
    ) {
        assertThat(actual)
            .as("Verify InspectionRouteGroupEquipment relevant properties")
            .satisfies(a -> assertThat(a.getIncluded()).as("check included").isEqualTo(expected.getIncluded()))
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteGroupEquipmentUpdatableRelationshipsEquals(
        InspectionRouteGroupEquipment expected,
        InspectionRouteGroupEquipment actual
    ) {
        assertThat(actual)
            .as("Verify InspectionRouteGroupEquipment relationships")
            .satisfies(a ->
                assertThat(a.getInspectionRouteGroup()).as("check inspectionRouteGroup").isEqualTo(expected.getInspectionRouteGroup())
            )
            .satisfies(a -> assertThat(a.getEquipment()).as("check equipment").isEqualTo(expected.getEquipment()));
    }
}
