package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InspectionRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordAllPropertiesEquals(InspectionRecord expected, InspectionRecord actual) {
        assertInspectionRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertInspectionRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordAllUpdatablePropertiesEquals(InspectionRecord expected, InspectionRecord actual) {
        assertInspectionRecordUpdatableFieldsEquals(expected, actual);
        assertInspectionRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordAutoGeneratedPropertiesEquals(InspectionRecord expected, InspectionRecord actual) {
        assertThat(actual)
            .as("Verify InspectionRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordUpdatableFieldsEquals(InspectionRecord expected, InspectionRecord actual) {
        assertThat(actual)
            .as("Verify InspectionRecord relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getMaintenanceDocument()).as("check maintenanceDocument").isEqualTo(expected.getMaintenanceDocument())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getExpectedStartDate()).as("check expectedStartDate").isEqualTo(expected.getExpectedStartDate()))
            .satisfies(a -> assertThat(a.getExpectedEndDate()).as("check expectedEndDate").isEqualTo(expected.getExpectedEndDate()))
            .satisfies(a -> assertThat(a.getStarted()).as("check started").isEqualTo(expected.getStarted()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getFinished()).as("check finished").isEqualTo(expected.getFinished()))
            .satisfies(a -> assertThat(a.getFinishedAt()).as("check finishedAt").isEqualTo(expected.getFinishedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordUpdatableRelationshipsEquals(InspectionRecord expected, InspectionRecord actual) {
        assertThat(actual)
            .as("Verify InspectionRecord relationships")
            .satisfies(a -> assertThat(a.getPlant()).as("check plant").isEqualTo(expected.getPlant()))
            .satisfies(a -> assertThat(a.getInspectionRoute()).as("check inspectionRoute").isEqualTo(expected.getInspectionRoute()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getStartedBy()).as("check startedBy").isEqualTo(expected.getStartedBy()))
            .satisfies(a -> assertThat(a.getFinishedBy()).as("check finishedBy").isEqualTo(expected.getFinishedBy()));
    }
}
