package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InspectionRecordGroupEquipmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordGroupEquipmentAllPropertiesEquals(
        InspectionRecordGroupEquipment expected,
        InspectionRecordGroupEquipment actual
    ) {
        assertInspectionRecordGroupEquipmentAutoGeneratedPropertiesEquals(expected, actual);
        assertInspectionRecordGroupEquipmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordGroupEquipmentAllUpdatablePropertiesEquals(
        InspectionRecordGroupEquipment expected,
        InspectionRecordGroupEquipment actual
    ) {
        assertInspectionRecordGroupEquipmentUpdatableFieldsEquals(expected, actual);
        assertInspectionRecordGroupEquipmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordGroupEquipmentAutoGeneratedPropertiesEquals(
        InspectionRecordGroupEquipment expected,
        InspectionRecordGroupEquipment actual
    ) {
        assertThat(actual)
            .as("Verify InspectionRecordGroupEquipment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordGroupEquipmentUpdatableFieldsEquals(
        InspectionRecordGroupEquipment expected,
        InspectionRecordGroupEquipment actual
    ) {
        assertThat(actual)
            .as("Verify InspectionRecordGroupEquipment relevant properties")
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordGroupEquipmentUpdatableRelationshipsEquals(
        InspectionRecordGroupEquipment expected,
        InspectionRecordGroupEquipment actual
    ) {
        assertThat(actual)
            .as("Verify InspectionRecordGroupEquipment relationships")
            .satisfies(a ->
                assertThat(a.getInspectionRecordGroup()).as("check inspectionRecordGroup").isEqualTo(expected.getInspectionRecordGroup())
            )
            .satisfies(a -> assertThat(a.getEquipment()).as("check equipment").isEqualTo(expected.getEquipment()));
    }
}
