package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InspectionRouteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteAllPropertiesEquals(InspectionRoute expected, InspectionRoute actual) {
        assertInspectionRouteAutoGeneratedPropertiesEquals(expected, actual);
        assertInspectionRouteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteAllUpdatablePropertiesEquals(InspectionRoute expected, InspectionRoute actual) {
        assertInspectionRouteUpdatableFieldsEquals(expected, actual);
        assertInspectionRouteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteAutoGeneratedPropertiesEquals(InspectionRoute expected, InspectionRoute actual) {
        assertThat(actual)
            .as("Verify InspectionRoute auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteUpdatableFieldsEquals(InspectionRoute expected, InspectionRoute actual) {
        assertThat(actual)
            .as("Verify InspectionRoute relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getMaintenancePlan()).as("check maintenancePlan").isEqualTo(expected.getMaintenancePlan()))
            .satisfies(a -> assertThat(a.getPeriodicity()).as("check periodicity").isEqualTo(expected.getPeriodicity()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getExpectedStartDate()).as("check expectedStartDate").isEqualTo(expected.getExpectedStartDate()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteUpdatableRelationshipsEquals(InspectionRoute expected, InspectionRoute actual) {
        assertThat(actual)
            .as("Verify InspectionRoute relationships")
            .satisfies(a -> assertThat(a.getPlant()).as("check plant").isEqualTo(expected.getPlant()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }
}
