package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InspectionRouteGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteGroupAllPropertiesEquals(InspectionRouteGroup expected, InspectionRouteGroup actual) {
        assertInspectionRouteGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertInspectionRouteGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteGroupAllUpdatablePropertiesEquals(InspectionRouteGroup expected, InspectionRouteGroup actual) {
        assertInspectionRouteGroupUpdatableFieldsEquals(expected, actual);
        assertInspectionRouteGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteGroupAutoGeneratedPropertiesEquals(InspectionRouteGroup expected, InspectionRouteGroup actual) {
        assertThat(actual)
            .as("Verify InspectionRouteGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteGroupUpdatableFieldsEquals(InspectionRouteGroup expected, InspectionRouteGroup actual) {
        assertThat(actual)
            .as("Verify InspectionRouteGroup relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteGroupUpdatableRelationshipsEquals(InspectionRouteGroup expected, InspectionRouteGroup actual) {
        assertThat(actual)
            .as("Verify InspectionRouteGroup relationships")
            .satisfies(a -> assertThat(a.getInspectionRoute()).as("check inspectionRoute").isEqualTo(expected.getInspectionRoute()))
            .satisfies(a -> assertThat(a.getSubGroup()).as("check subGroup").isEqualTo(expected.getSubGroup()))
            .satisfies(a -> assertThat(a.getEquipments()).as("check equipments").isEqualTo(expected.getEquipments()));
    }
}
