package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InspectionRouteRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteRecordAllPropertiesEquals(InspectionRouteRecord expected, InspectionRouteRecord actual) {
        assertInspectionRouteRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertInspectionRouteRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteRecordAllUpdatablePropertiesEquals(
        InspectionRouteRecord expected,
        InspectionRouteRecord actual
    ) {
        assertInspectionRouteRecordUpdatableFieldsEquals(expected, actual);
        assertInspectionRouteRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteRecordAutoGeneratedPropertiesEquals(
        InspectionRouteRecord expected,
        InspectionRouteRecord actual
    ) {
        assertThat(actual)
            .as("Verify InspectionRouteRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteRecordUpdatableFieldsEquals(InspectionRouteRecord expected, InspectionRouteRecord actual) {
        assertThat(actual)
            .as("Verify InspectionRouteRecord relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getMaintenanceDocument()).as("check maintenanceDocument").isEqualTo(expected.getMaintenanceDocument())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getExpectedStartDate()).as("check expectedStartDate").isEqualTo(expected.getExpectedStartDate()))
            .satisfies(a -> assertThat(a.getExpectedEndDate()).as("check expectedEndDate").isEqualTo(expected.getExpectedEndDate()))
            .satisfies(a -> assertThat(a.getStarted()).as("check started").isEqualTo(expected.getStarted()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getFinished()).as("check finished").isEqualTo(expected.getFinished()))
            .satisfies(a -> assertThat(a.getFinishedAt()).as("check finishedAt").isEqualTo(expected.getFinishedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRouteRecordUpdatableRelationshipsEquals(
        InspectionRouteRecord expected,
        InspectionRouteRecord actual
    ) {
        assertThat(actual)
            .as("Verify InspectionRouteRecord relationships")
            .satisfies(a -> assertThat(a.getStartedBy()).as("check startedBy").isEqualTo(expected.getStartedBy()))
            .satisfies(a -> assertThat(a.getFinishedBy()).as("check finishedBy").isEqualTo(expected.getFinishedBy()));
    }
}
