package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InspectionRecordGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordGroupAllPropertiesEquals(InspectionRecordGroup expected, InspectionRecordGroup actual) {
        assertInspectionRecordGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertInspectionRecordGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordGroupAllUpdatablePropertiesEquals(
        InspectionRecordGroup expected,
        InspectionRecordGroup actual
    ) {
        assertInspectionRecordGroupUpdatableFieldsEquals(expected, actual);
        assertInspectionRecordGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordGroupAutoGeneratedPropertiesEquals(
        InspectionRecordGroup expected,
        InspectionRecordGroup actual
    ) {
        assertThat(actual)
            .as("Verify InspectionRecordGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordGroupUpdatableFieldsEquals(InspectionRecordGroup expected, InspectionRecordGroup actual) {
        assertThat(actual)
            .as("Verify InspectionRecordGroup relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()))
            .satisfies(a -> assertThat(a.getFinished()).as("check finished").isEqualTo(expected.getFinished()))
            .satisfies(a -> assertThat(a.getFinishedAt()).as("check finishedAt").isEqualTo(expected.getFinishedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInspectionRecordGroupUpdatableRelationshipsEquals(
        InspectionRecordGroup expected,
        InspectionRecordGroup actual
    ) {
        assertThat(actual)
            .as("Verify InspectionRecordGroup relationships")
            .satisfies(a -> assertThat(a.getInspectionRecord()).as("check inspectionRecord").isEqualTo(expected.getInspectionRecord()))
            .satisfies(a -> assertThat(a.getParentGroup()).as("check parentGroup").isEqualTo(expected.getParentGroup()));
    }
}
