package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlantAllPropertiesEquals(Plant expected, Plant actual) {
        assertPlantAutoGeneratedPropertiesEquals(expected, actual);
        assertPlantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlantAllUpdatablePropertiesEquals(Plant expected, Plant actual) {
        assertPlantUpdatableFieldsEquals(expected, actual);
        assertPlantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlantAutoGeneratedPropertiesEquals(Plant expected, Plant actual) {
        assertThat(actual)
            .as("Verify Plant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlantUpdatableFieldsEquals(Plant expected, Plant actual) {
        assertThat(actual)
            .as("Verify Plant relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlantUpdatableRelationshipsEquals(Plant expected, Plant actual) {
        assertThat(actual)
            .as("Verify Plant relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()))
            .satisfies(a -> assertThat(a.getBusinessUnit()).as("check businessUnit").isEqualTo(expected.getBusinessUnit()));
    }
}
