package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RiskPeriodicityDeadlineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskPeriodicityDeadlineAllPropertiesEquals(RiskPeriodicityDeadline expected, RiskPeriodicityDeadline actual) {
        assertRiskPeriodicityDeadlineAutoGeneratedPropertiesEquals(expected, actual);
        assertRiskPeriodicityDeadlineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskPeriodicityDeadlineAllUpdatablePropertiesEquals(
        RiskPeriodicityDeadline expected,
        RiskPeriodicityDeadline actual
    ) {
        assertRiskPeriodicityDeadlineUpdatableFieldsEquals(expected, actual);
        assertRiskPeriodicityDeadlineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskPeriodicityDeadlineAutoGeneratedPropertiesEquals(
        RiskPeriodicityDeadline expected,
        RiskPeriodicityDeadline actual
    ) {
        assertThat(actual)
            .as("Verify RiskPeriodicityDeadline auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskPeriodicityDeadlineUpdatableFieldsEquals(
        RiskPeriodicityDeadline expected,
        RiskPeriodicityDeadline actual
    ) {
        assertThat(actual)
            .as("Verify RiskPeriodicityDeadline relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDeadline()).as("check deadline").isEqualTo(expected.getDeadline()))
            .satisfies(a -> assertThat(a.getDeadlineUnit()).as("check deadlineUnit").isEqualTo(expected.getDeadlineUnit()))
            .satisfies(a -> assertThat(a.getPeriodicity()).as("check periodicity").isEqualTo(expected.getPeriodicity()))
            .satisfies(a -> assertThat(a.getPeriodicityUnit()).as("check periodicityUnit").isEqualTo(expected.getPeriodicityUnit()))
            .satisfies(a -> assertThat(a.getRecommendations()).as("check recommendations").isEqualTo(expected.getRecommendations()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskPeriodicityDeadlineUpdatableRelationshipsEquals(
        RiskPeriodicityDeadline expected,
        RiskPeriodicityDeadline actual
    ) {
        // empty method
    }
}
