package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RiskRecommendationTranslationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskRecommendationTranslationAllPropertiesEquals(
        RiskRecommendationTranslation expected,
        RiskRecommendationTranslation actual
    ) {
        assertRiskRecommendationTranslationAutoGeneratedPropertiesEquals(expected, actual);
        assertRiskRecommendationTranslationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskRecommendationTranslationAllUpdatablePropertiesEquals(
        RiskRecommendationTranslation expected,
        RiskRecommendationTranslation actual
    ) {
        assertRiskRecommendationTranslationUpdatableFieldsEquals(expected, actual);
        assertRiskRecommendationTranslationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskRecommendationTranslationAutoGeneratedPropertiesEquals(
        RiskRecommendationTranslation expected,
        RiskRecommendationTranslation actual
    ) {
        assertThat(actual)
            .as("Verify RiskRecommendationTranslation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskRecommendationTranslationUpdatableFieldsEquals(
        RiskRecommendationTranslation expected,
        RiskRecommendationTranslation actual
    ) {
        assertThat(actual)
            .as("Verify RiskRecommendationTranslation relevant properties")
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskRecommendationTranslationUpdatableRelationshipsEquals(
        RiskRecommendationTranslation expected,
        RiskRecommendationTranslation actual
    ) {
        assertThat(actual)
            .as("Verify RiskRecommendationTranslation relationships")
            .satisfies(a ->
                assertThat(a.getRiskPeriodicityDeadline())
                    .as("check riskPeriodicityDeadline")
                    .isEqualTo(expected.getRiskPeriodicityDeadline())
            );
    }
}
