package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ROIAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertROIAllPropertiesEquals(ROI expected, ROI actual) {
        assertROIAutoGeneratedPropertiesEquals(expected, actual);
        assertROIAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertROIAllUpdatablePropertiesEquals(ROI expected, ROI actual) {
        assertROIUpdatableFieldsEquals(expected, actual);
        assertROIUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertROIAutoGeneratedPropertiesEquals(ROI expected, ROI actual) {
        assertThat(actual)
            .as("Verify ROI auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertROIUpdatableFieldsEquals(ROI expected, ROI actual) {
        assertThat(actual)
            .as("Verify ROI relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getMaxTemp()).as("check maxTemp").isEqualTo(expected.getMaxTemp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertROIUpdatableRelationshipsEquals(ROI expected, ROI actual) {
        assertThat(actual)
            .as("Verify ROI relationships")
            .satisfies(a -> assertThat(a.getThermogram()).as("check thermogram").isEqualTo(expected.getThermogram()));
    }
}
