package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ThermographicInspectionRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThermographicInspectionRecordAllPropertiesEquals(
        ThermographicInspectionRecord expected,
        ThermographicInspectionRecord actual
    ) {
        assertThermographicInspectionRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertThermographicInspectionRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThermographicInspectionRecordAllUpdatablePropertiesEquals(
        ThermographicInspectionRecord expected,
        ThermographicInspectionRecord actual
    ) {
        assertThermographicInspectionRecordUpdatableFieldsEquals(expected, actual);
        assertThermographicInspectionRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThermographicInspectionRecordAutoGeneratedPropertiesEquals(
        ThermographicInspectionRecord expected,
        ThermographicInspectionRecord actual
    ) {
        assertThat(actual)
            .as("Verify ThermographicInspectionRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThermographicInspectionRecordUpdatableFieldsEquals(
        ThermographicInspectionRecord expected,
        ThermographicInspectionRecord actual
    ) {
        assertThat(actual)
            .as("Verify ThermographicInspectionRecord relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getServiceOrder()).as("check serviceOrder").isEqualTo(expected.getServiceOrder()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a ->
                assertThat(a.getAnalysisDescription()).as("check analysisDescription").isEqualTo(expected.getAnalysisDescription())
            )
            .satisfies(a -> assertThat(a.getCondition()).as("check condition").isEqualTo(expected.getCondition()))
            .satisfies(a -> assertThat(a.getDeltaT()).as("check deltaT").isEqualTo(expected.getDeltaT()))
            .satisfies(a -> assertThat(a.getPeriodicity()).as("check periodicity").isEqualTo(expected.getPeriodicity()))
            .satisfies(a -> assertThat(a.getDeadlineExecution()).as("check deadlineExecution").isEqualTo(expected.getDeadlineExecution()))
            .satisfies(a -> assertThat(a.getNextMonitoring()).as("check nextMonitoring").isEqualTo(expected.getNextMonitoring()))
            .satisfies(a -> assertThat(a.getRecommendations()).as("check recommendations").isEqualTo(expected.getRecommendations()))
            .satisfies(a -> assertThat(a.getFinished()).as("check finished").isEqualTo(expected.getFinished()))
            .satisfies(a -> assertThat(a.getFinishedAt()).as("check finishedAt").isEqualTo(expected.getFinishedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThermographicInspectionRecordUpdatableRelationshipsEquals(
        ThermographicInspectionRecord expected,
        ThermographicInspectionRecord actual
    ) {
        assertThat(actual)
            .as("Verify ThermographicInspectionRecord relationships")
            .satisfies(a -> assertThat(a.getPlant()).as("check plant").isEqualTo(expected.getPlant()))
            .satisfies(a -> assertThat(a.getRoute()).as("check route").isEqualTo(expected.getRoute()))
            .satisfies(a -> assertThat(a.getEquipment()).as("check equipment").isEqualTo(expected.getEquipment()))
            .satisfies(a -> assertThat(a.getComponent()).as("check component").isEqualTo(expected.getComponent()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getFinishedBy()).as("check finishedBy").isEqualTo(expected.getFinishedBy()))
            .satisfies(a -> assertThat(a.getThermogram()).as("check thermogram").isEqualTo(expected.getThermogram()))
            .satisfies(a -> assertThat(a.getThermogramRef()).as("check thermogramRef").isEqualTo(expected.getThermogramRef()));
    }
}
