package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ThermogramAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThermogramAllPropertiesEquals(Thermogram expected, Thermogram actual) {
        assertThermogramAutoGeneratedPropertiesEquals(expected, actual);
        assertThermogramAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThermogramAllUpdatablePropertiesEquals(Thermogram expected, Thermogram actual) {
        assertThermogramUpdatableFieldsEquals(expected, actual);
        assertThermogramUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThermogramAutoGeneratedPropertiesEquals(Thermogram expected, Thermogram actual) {
        assertThat(actual)
            .as("Verify Thermogram auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThermogramUpdatableFieldsEquals(Thermogram expected, Thermogram actual) {
        assertThat(actual)
            .as("Verify Thermogram relevant properties")
            .satisfies(a -> assertThat(a.getImagePath()).as("check imagePath").isEqualTo(expected.getImagePath()))
            .satisfies(a -> assertThat(a.getAudioPath()).as("check audioPath").isEqualTo(expected.getAudioPath()))
            .satisfies(a -> assertThat(a.getImageRefPath()).as("check imageRefPath").isEqualTo(expected.getImageRefPath()))
            .satisfies(a -> assertThat(a.getMinTemp()).as("check minTemp").isEqualTo(expected.getMinTemp()))
            .satisfies(a -> assertThat(a.getAvgTemp()).as("check avgTemp").isEqualTo(expected.getAvgTemp()))
            .satisfies(a -> assertThat(a.getMaxTemp()).as("check maxTemp").isEqualTo(expected.getMaxTemp()))
            .satisfies(a -> assertThat(a.getEmissivity()).as("check emissivity").isEqualTo(expected.getEmissivity()))
            .satisfies(a -> assertThat(a.getSubjectDistance()).as("check subjectDistance").isEqualTo(expected.getSubjectDistance()))
            .satisfies(a -> assertThat(a.getAtmosphericTemp()).as("check atmosphericTemp").isEqualTo(expected.getAtmosphericTemp()))
            .satisfies(a -> assertThat(a.getReflectedTemp()).as("check reflectedTemp").isEqualTo(expected.getReflectedTemp()))
            .satisfies(a -> assertThat(a.getRelativeHumidity()).as("check relativeHumidity").isEqualTo(expected.getRelativeHumidity()))
            .satisfies(a -> assertThat(a.getCameraLens()).as("check cameraLens").isEqualTo(expected.getCameraLens()))
            .satisfies(a -> assertThat(a.getCameraModel()).as("check cameraModel").isEqualTo(expected.getCameraModel()))
            .satisfies(a -> assertThat(a.getImageResolution()).as("check imageResolution").isEqualTo(expected.getImageResolution()))
            .satisfies(a -> assertThat(a.getSelectedRoiId()).as("check selectedRoiId").isEqualTo(expected.getSelectedRoiId()))
            .satisfies(a -> assertThat(a.getMaxTempRoi()).as("check maxTempRoi").isEqualTo(expected.getMaxTempRoi()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThermogramUpdatableRelationshipsEquals(Thermogram expected, Thermogram actual) {
        assertThat(actual)
            .as("Verify Thermogram relationships")
            .satisfies(a -> assertThat(a.getEquipment()).as("check equipment").isEqualTo(expected.getEquipment()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }
}
