package com.tech.thermography.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserInfoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserInfoAllPropertiesEquals(UserInfo expected, UserInfo actual) {
        assertUserInfoAutoGeneratedPropertiesEquals(expected, actual);
        assertUserInfoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserInfoAllUpdatablePropertiesEquals(UserInfo expected, UserInfo actual) {
        assertUserInfoUpdatableFieldsEquals(expected, actual);
        assertUserInfoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserInfoAutoGeneratedPropertiesEquals(UserInfo expected, UserInfo actual) {
        assertThat(actual)
            .as("Verify UserInfo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserInfoUpdatableFieldsEquals(UserInfo expected, UserInfo actual) {
        assertThat(actual)
            .as("Verify UserInfo relevant properties")
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserInfoUpdatableRelationshipsEquals(UserInfo expected, UserInfo actual) {
        assertThat(actual)
            .as("Verify UserInfo relationships")
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()));
    }
}
