package com.tech.thermography.domain.enumeration;

/**
 * The EquipmentType enumeration.
 */
public enum EquipmentType {
    AUTOTRANSFORMER,
    BATTERY_BANK,
    BLOCKING_COIL,
    BUSBAR,
    BUSHING,
    CAPACITOR_BANK,
    CAPACITIVE_DIVIDER,
    CAPACITIVE_POTENTIAL_TRANSFORMER,
    CIRCUIT_BREAKER,
    CURRENT_TRANSFORMER,
    DISCONNECT_SWITCH,
    DISTRIBUTION_LINE,
    ELECTRICAL_PANEL,
    EMERGENCY_GENERATOR,
    FUSE_SWITCH,
    GENERATOR,
    INDUCTIVE_POTENTIAL_TRANSFORMER,
    METAL_CLAD_SWITCHGEAR,
    POTENTIAL_TRANSFORMER,
    POWER_TRANSFORMER,
    PROTECTION_CONTROL_PANEL,
    PROTECTION_SYSTEM,
    RECTIFIER,
    RELAY,
    SERIES_COMPENSATOR,
    SHUNT_REACTOR,
    STATIC_COMPENSATOR,
    SURGE_ARRESTER,
    SYNCHRONOUS_CONDENSER,
    TRANSMISSION_TOWER,
}
